name: Horace CI

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  test-and-lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test:standalone
    - name: Run linting
      run: npm run lint
